# refer this file to create GitHub Actions workflow
dist: xenial

sudo: required

language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - /^release-.*$/
    - /^test-.*$/


### 搭建 python 3.7 环境
before_install:
  # 安装 python 环境
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install python3.7
  # 修改 python 版本的使用优先级
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
  # 修改 python 默认使用的版本
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 100
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 150

### 安装相关依赖
install:
  - sudo apt-get -y install python3-pip
  - sudo pip3 install -r ./requirements.txt

### 获取 graph 测试服务
before_script:
  - sudo python src/deploy_start.py all
  - cd src/config && unzip dataset.zip && cd ../..

### 执行测试脚本
jobs:
  include:
    - script:
        - sudo python src/test_start.py loader
    - script:
        - sudo python src/test_start.py server
    - script:
        - sudo python src/test_start.py hubble
    - srcipt:
        - sudo python src/test_start.py server

# push report_html to my repos
#after_failure:
#  - git add *.html
#  - git commit -m 'fail report detail'
#  - git push
